# Site settings
title: 'Nice Shot'  # Your Title
tagline: 'To find something interesting'  # A brief tagline for your site
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
baseurl: # the subpath of your site, e.g. /blog/
codeurl: /code/
fragmenturl: /fragment/

# Personal info
avatar: //tva2.sinaimg.cn/crop.0.0.640.640.300/837c3916jw8f3phjbg2fij20hs0hsmxf.jpg
email: hufo125@gmail.com
github: https://github.com/humyna
weibo: http://tec.zoio.info
twitter: http://tec.zoio.info
music: http://tec.zoio.info

# Logo setting
logocolor: '#000'
